name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run-Lint
      - run: ./gradlew lint

      - name: Upload html test report
        uses: actions/upload-artifact@v2
          whith:
            name: lint_html_report
            path: app/build/reports/lint-results-debug.html



